<?php

namespace Modules\Category\Models;

use Illuminate\Database\Eloquent\Model;
use Laravolt\Suitable\AutoFilter;
use Laravolt\Suitable\AutoSort;
use Sofa\Eloquence\Eloquence;

class Category extends Model
{
    use AutoSort, AutoFilter;
    use Eloquence;

    protected $table = 'categories';

    protected $guarded = [];

    protected $searchableColumns = ['title', 'slug'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::created(function ($model) {
            Category::categoryUpdate();
        });

        self::updated(function ($model) {
            Category::categoryUpdate();
        });

        self::deleted(function ($model) {
            Category::categoryUpdate();
        });
    }

    public static function categoryUpdate()
    {
        $category = json_encode(
            Category::with('childrenRecursive')
                ->whereNull('parent_id')
                ->orderBy('title')
                ->get()
                ->toArray()
        );
        setting()->set('List Category', $category);
        $settings = setting()->save();
    }

    /**
     * Get the parent.
     */
    public function parent()
    {
        return $this->belongsTo('Modules\Category\Models\Category', 'parent_id');
    }

    public function getParentTitleAttribute()
    {
        $parent = $this->parent->title ?? ' - ';

        return $parent;
    }

    // loads only direct children - 1 level
    public function children()
    {
        return $this->hasMany('Modules\Category\Models\Category', 'parent_id');
    }

    // recursive, loads all descendants
    public function childrenRecursive()
    {
        return $this->children()->orderBy('title')->with('childrenRecursive');
    }

    // all ascendants
    public function parentRecursive()
    {
        return $this->parent()->with('parentRecursive');
    }
}
